server:
  port: 8083
spring:
  application:
    name: eureka-client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://replica1:8081/eureka/,http://replica2:8082/eureka/
