server:
  port: 8014
spring:
  application:
    name: config-security-server

  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/liliwo/springclouddemo-config.git
          username: 2629910752@qq.com
          password: linjinli199534
          clone-on-start: true #开启启动时直接从git获取配置
  security: #配置用户名和密码
    user:
      name: lwoo
      password: 123456

