server:
  port: 8034
  servlet:
    session:
      cookie:
        name: OAUTH2-CLIENT-SESSIONID #防止Cookie冲突，冲突会导致登录验证不通过
oauth2-server-url: http://localhost:8033/
spring:
  application:
    name: oauth2-client
security:
  oauth2:
    client:
      client-id: admin
      client-secret: admin123456
      access-token-uri: ${oauth2-server-url}/oauth/token
      user-authorization-uri: ${oauth2-server-url}/oauth/authorize
    resource:
      jwt:
        key-uri: ${oauth2-server-url}/oauth/token_key

