server:
  port: 8011

spring:
  application:
    name: zuul-proxy
eureka:
  client:
    service-url:
      defaultZone: http://replica1:8081//eureka/,http://replica2:8082//eureka/
    fetch-registry: true
    register-with-eureka: true
zuul:
  routes:  #默认路由规则 自动配置的路由以服务名称为匹配路径
    user-service:
      path: /userService/** #匹配/userService/**的请求路由到user-service服务
    fegin-service:
      path: /feginService/** #/feignService/**的请求路由到feign-service
  prefix: /proxy  #配置访问前缀
  sensitive-headers: Set-Cookie,Authorization  #配置过滤敏感的请求头信息，设置为空就不会过滤
#  add-host-header: true #设置为true重定向是会添加host请求头
#  retryable: true # 关闭重试机制
  PreLogFilter: #禁用PreLogFilter的配置
    pre:
      disable: false
#  ignored-services: user-service,feign-service #关闭默认路由配置
management: #开启查看路由的端点   http://localhost:8011/actuator/routes //查看简单路由信息 http://localhost:8011/actuator/routes/details 查看详细路由信息
  endpoints:
    web:
      exposure:
        include: 'routes'


#hystrix:
#  command: #用于控制HystrixCommand的行为
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 1000 #配置HystrixCommand执行的超时时间，执行超过该时间会进行服务降级处理
#
#ribbon: #全局配置
#  ConnectTimeout: 1000 #服务请求连接超时时间（毫秒）
#  ReadTimeout: 3000 #服务请求处理超时时间（毫秒）