server:
  port: 8022
spring:
  application:
    name: consul-ribbon-service
  cloud:
    consul: #Consul服务注册发现配置
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
service-url:
  user-service: http://consul-user-service