spring:
  application:
    name: admin-security-server
  security: # 配置登录用户名和密码
    user:
      name: lwoo
      password: 123456
  boot:  # 不显示admin-security-server的监控信息
    admin:
      discovery:
        ignored-services: ${spring.application.name}
server:
  port: 8031
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://replica1:8081/eureka/,http://replica2:8082/eureka/
