server:
  port: 8081
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: replica1
  client:
    serviceUrl:
      defaultZone: http://replica2:8082/eureka/
    fetch-registry: true
    register-with-eureka: true
  server:
    enable-self-preservation: false


