
spring:
  application:
    name: admin-client
#  boot:
#    admin:
#      client:
#        url: http://localhost:8028 #≈‰÷√admin-serverµÿ÷∑
server:
  port: 8029
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  file:
    name: admin-client.log

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://replica1:8081/eureka/,http://replica2:8082/eureka/