server:
  port: 8003
spring:
  application:
    name: ribbon-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://replica1:8081//eureka/,http://replica2:8082//eureka/
service-url:
  user-service: http://user-service
