server:
  port: 8020
spring:
  application:
    name: ribbon-service
  zipkin: #   启动命令 java -jar zipkin-server-2.12.9-exec.jar
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 0.1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://replica1:8081/eureka/,http://replica2:8082/eureka/
service-url:
  user-service: http://user-service

